### ISSUE TITLE
sort by related models

### ISSUE THREAD

**Issue by mjamroz** [jedrzej/sortable#18]
It is possible to sort by related model field?

**Comment by miguelangelorodrigues** [comment]
Yes I'm with same issue now...

**Comment by MikeSheward** [comment]
I'd be interested to see this too, it manages to interact with related models via the jedrzej/searchable but not this one

**Comment by jedrzej** [comment]
@mjamroz @BlitZ-UK: how would you normally sort by related model's field using Eloquent query builder? The URL parameters the sortable gets need to be translated into a query built with that builder, I'm not sure what's the best way to get that to work for all relation types.

**Comment by mjamroz** [comment]
That code below is horrible terrible, but it seems to works for 1:1 relationship at least, and it works only for laravel convention of related field (singular_id).
```php
    public function sorts() 
    {
        list($related_model, $related_field) = explode(":", "vendorinfo:compound_code"); // that one from the url

        $rel_model = call_user_func(get_class($this)."::".$related_model);

        $this_keyname = $this->getKeyName();
        $this_table = str_plural($this->getTable()); 

        $rel_fieldname = str_singular($this_table)."_".$this_keyname;

        $child_table = str_plural(str_slug(class_basename(get_class($rel_model->getRelated()))));

        $ordered = $this
            ->join($child_table, $child_table.".".$rel_fieldname, "=", $this_table.".".$this_keyname)
            ->orderBy($child_table.".".$related_field)->first();

// $ordered  is ordered by compound_code of vendorinfo relation
      
    }
```

**Comment by ghost** [comment]
@jedrzej did some experiments. This is what I came up with:

Given these two models: User and Post
User hasMany Post

```php
/**
     * Applies criterion to query.
     *
     * @param Builder $builder query builder
     */
    public function apply(Builder $builder)
    {
        $sortMethod = 'sort' . studly_case($this->getField());
        if (method_exists($builder->getModel(), $sortMethod)) {
            call_user_func_array([$builder->getModel(), $sortMethod], [$builder, $this->getOrder()]);
        }
        $values = explode('.', $this->getField());
        if (is_array($values) && count($values) === 2) {
            list($relation, $this->field) = explode(".", $this->getField());
            $sortedModel = $builder->getModel();
            $sortedTable = $sortedModel->getTable();
            $builder->join($relation, $relation . '.' . $sortedModel->getForeignKey(), '=', $sortedTable . '.' . $sortedModel->getKeyName())
                    ->orderBy($relation . '.' . $this->getField(), $this->getOrder());
        } else {
            $builder->orderBy($this->getField(), $this->getOrder());
        }
    }

```

`?sortBy=posts.created_at,desc` will return the users ordered by posts' created_ad field.

I have tried also with User hasOne Post and it works.

Now the tricky part: 
`?sortBy[]=posts.created_at,desc&sortBy[]=created_at,asc` this won't work because `created_at`  will be ambigous.

```sql
Integrity constraint violation: 1052 Column 'created_at' in order clause is ambiguous (SQL: select * from `users` inner join `posts` on `posts`.`user_id` = `users`.`id` order by `posts`.`created_at` desc, `created_at` asc)
```

In this case I wouldn't know how exactly to fix it. The last element of `sort[]` should win? Ran out of ideas for this one.

There are some other cases like nested relationships, for example `posts.comments.created_at,desc`. In this case I really have no clue.
