### ISSUE TITLE
Allow dot in field name

### ISSUE THREAD

**Issue by raitisg** [jedrzej/sortable#19]
I have a working query in v0.0.9:

```
Product
	::with(['brand'])
	->leftJoin('brands as brand', 'brand.id', '=', 'products.brand_id')
	->sorted('brand.title,desc')
	->paginate();
```

In v0.0.10 this is no longer working as `validateFieldName` function rejects `brand.title` as it contains ".". It seems that allowing dot, everything still works as intended.

**Comment by jedrzej** [comment]
Good catch @raitisg. This should be fixed already in 0.0.11
